### PR TITLE
add initial support for semantic_manifest files

### LINKED ISSUE #105: Add support for semantic manifest files
It would be great if this library supported [semantic_manifest](https://docs.getdbt.com/docs/dbt-cloud-apis/sl-manifest) parsing.

### PR DESCRIPTION
**Pull request by MiConnell**
This PR begins the process for supporting semantic manifest files. I'd love your feedback on the logic I set up and if I missed anything. As of now, there's no semantic_manifest schema defined in dbt's schema site, but [there's some discussion of that getting updated shortly](https://github.com/dbt-labs/docs.getdbt.com/issues/4369). 
Fixes #105

### CODE REVIEW

**Comment by yu-iskw** [comment]
@MiConnell Thank you for opening this. I want to support `semantic_manifest.json` after it is open-sourced, because we can't reproduce to generate the class without the schema.

**Comment by yu-iskw** [comment]
@MiConnell Let me close this once. Please feel free to reopen it, when it gets ready.

**Comment by pgoslatara** [comment]
@yu-iskw What actions do you need before this is considered ready? I see `semantic_manifest.json` listed [here](https://docs.getdbt.com/reference/artifacts/other-artifacts#semantic_manifestjson) so I'm not sure what else is required before we can add this to `dbt-artifacts-parser`.

**Comment by yu-iskw** [comment]
As far as I know, `semantic_manifest.json` isn't listed at the subsequent links, because it isn't a part of dbt-core I suppose. But, I don't know dbt Labs make it public. We need JSON schemas which are publicly available to maintain this project so that any developer of this project can regenerate pydantic classes. 

- https://schemas.getdbt.com/
- https://github.com/dbt-labs/dbt-core/tree/main/schemas/dbt

**Comment by MiConnell** [comment]
To be fair [the example semantic manifest file on the docs site](https://docs.getdbt.com/docs/dbt-cloud-apis/sl-manifest) wasn't even up to date, [I opened a PR to add missing fields](https://github.com/dbt-labs/docs.getdbt.com/pull/5922) so who knows what the actual schema is.

**Comment by yu-iskw** [comment]
It is an example of `semantic_manifest.json`, not the JSON schema. We need the complete JSON schema to generate a pydantic class.

**Pull request closed without merging**
