### PR TITLE
Setting namespace to prevent warning

### PR DESCRIPTION
**Pull request by pgoslatara**
When importing the `parse_manifest` function, a Pydantic warning is raised. This PR follows the Pydantic [docs](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.protected_namespaces) by overwriting the default protected namespace to prevent this warning (and the unsightly message it prints to console).

Replication:
```shell
➜  tmp python3.11 -m virtualenv .venv && source .venv/bin/activate
created virtual environment CPython3.11.6.final.0-64 in 69ms
  creator CPython3Posix(dest=/home/<REDACTED>/tmp/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/<REDACTED>/.local/share/virtualenv)
    added seed packages: pip==24.0, setuptools==70.0.0, wheel==0.43.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
(.venv) ➜  tmp pip install dbt-artifacts-parser
...

Installing collected packages: typing-extensions, annotated-types, pydantic-core, pydantic, dbt-artifacts-parser
Successfully installed annotated-types-0.7.0 dbt-artifacts-parser-0.7.0 pydantic-2.8.2 pydantic-core-2.20.1 typing-extensions-4.12.2

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: pip install --upgrade pip
(.venv) ➜  tmp python
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dbt_artifacts_parser.parser import parse_manifest
/home/<REDACTED>/tmp/.venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:161: UserWarning: Field "model_unique_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
>>> 
```

The warning is also visible in previous runs of the `test.yml` workflow, example [here](https://github.com/yu-iskw/dbt-artifacts-parser/actions/runs/9752749132/job/26916818350).

### CODE REVIEW

**Comment by pgoslatara** [comment]
@yu-iskw Gentle nudge on this one. I'm building a tool on top of `dbt-artifacts-parser` and it's getting a little annoying getting warnings every time it's invoked.

**Comment by yu-iskw** [comment]
@pgoslatara Thank you for raising it. But, can you figure out if there is another approach to turn off the warnings, as I don't want to directly edit generated classes due to the maintainability. The discussion in https://github.com/yu-iskw/dbt-artifacts-parser/pull/107 might be useful to understand the context behind it. 

For instance, I tried to introduce base classes by the artifact type in order to control model configs. But, unfortunately, I don't have much time to delve into the approach at the moment. 
https://github.com/yu-iskw/dbt-artifacts-parser/pull/107

**Comment by pgoslatara** [comment]
@yu-iskw Thanks for looking into this PR! Please note that I am rather new to Pydantic so my understanding/terminology may be incorrect.

> But, can you figure out if there is another approach to turn off the warnings, as I don't want to directly edit generated classes due to the maintainability.

Yes! Another approach to silence the warning would be this:

```python
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings(
        "ignore",
        category=UserWarning
    )
    import dbt_artifacts_parser
```
My concern with this approach is that I have to apply it in every file where `dbt_artifacts_parser` is imported. And while this prevents the warning message, it only works for me. I'd like to solve this for everyone using this package, hence the approach in the PR where I tried to tackle the issue as specifically as possible while following Pydantic's advice at the same time.

**Comment by yu-iskw** [comment]
@pgoslatara Please feel free re-open the pull request, if you still want to solve the issue. However, manifest v12 doesn't have the property `model_unique_id` any more. So, the warning message shouldn't appear on manifest v12. I understand the manifest schema of the old versions have `model_unique_id` that violates the naming manner of Pydantic v2. But, I don't think we have to solve this right now.

**Pull request closed without merging**
