### PR TITLE
Adding time_spine field for manifest

### PR DESCRIPTION
**Pull request by pgoslatara**
### **User description**
The latest version of `manifest.json` from dbt Cloud contains a `time_spine` field for nodes. This PR adds this field so manifests can be parsed.

Extra info: this is what the `metadata` field looks like from the `manifest.json` I downloaded:
```json
{
    "metadata": {
        "dbt_schema_version": "https://schemas.getdbt.com/dbt/manifest/v12.json",
        "dbt_version": "2024.9.239",
        ...
    },
```

___

### **PR Type**
enhancement

___

### **Description**
- Added a new `time_spine` field to the `Nodes4` class in the `manifest_v12.py` file.
- This field is optional and allows for parsing the `time_spine` attribute from the latest `manifest.json` version.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>manifest_v12.py</strong><dd><code>Add `time_spine` field to `Nodes4` class in manifest parser</code></dd></summary>
<hr>

dbt_artifacts_parser/parsers/manifest/manifest_v12.py

<li>Added <code>time_spine</code> field to <code>Nodes4</code> class.<br> <li> The <code>time_spine</code> field is optional and of type <code>str</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/yu-iskw/dbt-artifacts-parser/pull/112/files#diff-b56fba67732fa72f0d8aa3ebe904809d0085f243ba88a9e6a2a4a037cb027eaa">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by pgoslatara** [comment]
Ahh, just cam across [this](https://schemas.getdbt.com/dbt/manifest/v12/index.html#nodes_additionalProperties_anyOf_i4_time_spine_anyOf_i0_custom_granularities), looks like `time_spine` is not a simple string.

**Comment by pgoslatara** [comment]
Updated!

**Comment by yu-iskw** [comment]
@pgoslatara Thank you for the contribution. But, I think supporting the feature is a little early, as it will be released as a part of dbt-core 1.9.

1. We don't change the pydantic class by hand, as we generate pydantic classess from the JSON schemas of dbt-core.
    - https://github.com/dbt-labs/dbt-core/tree/main/schemas/dbt
2. According to my research, the property was added as a part of dbt 1.9 which isn't released yet. I want to support stable releases to dbt-core versions, as properties which aren't released yet are potentially changed until the release. So, I want to update the pydantic class to manifest v12 after dbt-core 1.9 is released.

**Comment by pgoslatara** [comment]
Thanks @yu-iskw!

What does this mean for supporting dbt Cloud? There is now a [versionless](https://docs.getdbt.com/docs/dbt-versions/upgrade-dbt-version-in-cloud#versionless) option, in fact this will soon become the only option ([doc](https://docs.getdbt.com/docs/dbt-versions/versionless-cloud#:~:text=Going%20forward%2C%20%E2%80%9CVersionless%E2%80%9D%20will%20be%20how%20all%20customers%20are%20going%20to%20access%20new%20functionality%20and%20ongoing%20support%20in%20dbt%20Cloud.)) and is currently the recommended option ([doc](https://docs.getdbt.com/docs/dbt-versions/upgrade-dbt-version-in-cloud#:~:text=go%20Versionless%20(recommended))). Does this mean `dbt-artifacts-parser` will be incompatible with versionless dbt Cloud artifacts?

**Comment by yu-iskw** [comment]
@pgoslatara 

This project mainly supports dbt Core, because the JSON schema for dbt Cloud aren't available in public. For instance, as far as I know, `semantic_manifest.json` isn't available. So, we can't fully support dbt Cloud right now. So, we can't generate a pydantic class for that. Basically, we can generate pydantic classes based on JSON schemas of dbt Core. 

Meanwhile, we have evolved dbt artifacts of dbt Core as upgrading the version like manifest v10, v11 and v 12. If we upgrade the versions of artifacts in the future, generated artifacts in dbt Cloud have to follow the versions as well regardless versionless. Each artifacts has a property about a dbt version. As the stable version of dbt Core 1.9 isn't released yet, it might be early to update manifest v12 based on dbt Core 1.9.

https://github.com/dbt-labs/dbt-core/blob/3308a4365ed7a0aebea602b4444db2b08552ef37/schemas/dbt/manifest/v12.json#L14-L17

**Comment by yu-iskw** [comment]
@pgoslatara We have released v0.8.0 to catch up with the schema of dbt-core 1.9. Please feel free to re-open it, if you find anything wrong.

https://pypi.org/project/dbt-artifacts-parser/0.8.0/

**Comment by pgoslatara** [comment]
Thanks @yu-iskw, looks like 0.8.0 includes these changes so all good from my side.

**Pull request closed without merging**
