### PR TITLE
migrate to pydantic v2

### PR DESCRIPTION
**Pull request by hiro-o918**
## What
- **Migrate Generated Schema to Pydantic v2 (Current Latest Major Version)**
  - Major changes in this PR can be seen in the following commit:
    - https://github.com/yu-iskw/dbt-artifacts-parser/pull/66/commits/84bb5bb2513daf4302d880f5018780f7d7fb620d
- **Addition of `py.typed` File:**
  - A `py.typed` file has been added to indicate that this package is typed, enhancing type-checking compatibility.
    - Reference for Typed Packages: [Mypy Documentation](https://mypy.readthedocs.io/en/stable/installed_packages.html)
    - Related Discussion on Flit: [Flit Issue #520](https://github.com/pypa/flit/issues/520)

## Concerns

I am not confident about manual operations after running `./dev/generate_parser_classes.sh`.
Please feel free to edit this PR or create a new one if necessary.

### CODE REVIEW

**Comment by yu-iskw** [comment]
Thank you for the pull request. I haven't designed how to support pydantic 2 yet. But, if possible, I want to seek any way to support both of pydantic 1 and 2, because some users still have to use pydantic 1 due to their dependencies. Meanwhile, as the version of dbt Core gets upgraded, new artifacts (e.g. manifest v12) will be supported. If we once support only pydantic 2, such users won't use it any more. I don't think we have to support both in a single code base. We can also publish different python package with pydantic 2, for instance. Do you have any good ideas for that purpose?

**Comment by yu-iskw** [comment]
@hiro-o918 Magnificent! Thank you for the details. Let me consider the direction for a while. I will get back to you.

**Comment by natarajanc-prodigygame** [comment]
hello @yu-iskw  thank you for building this package - it seems airflow 2.8.0 is now  only [supporting](https://raw.githubusercontent.com/apache/airflow/constraints-2.8.0/constraints-3.10.txt) pydantic 2 so it would be great when you get a chance to update this package to support pydantic 2

**Comment by yu-iskw** [comment]
@hiro-o918 Sorry for the delay of my reply. I decided the version compatibility on pydantic. And let me open another to align them instead of the pull request. I appreciate your contribution. I will publish v0.7 to be compatible to pydantic v2 soon. If there is anything wrong with it in your application, please let me know.

https://github.com/yu-iskw/dbt-artifacts-parser/pull/66

**Pull request closed without merging**
