### PR TITLE
Add support for dbt manifest.json v6

### PR DESCRIPTION
**Pull request by nabilm**
Added support for manifest v6  https://schemas.getdbt.com/dbt/manifest/v6/index.html
Added needed tests
Fixed some typos

### CODE REVIEW

**Comment by yu-iskw** [comment]
@nabilm Thank you for the PR. Can you check the lint results and separate code format from the PR? It is difficult to see difference on `dbt_artifacts_parser/parsers/manifest/manifest_v5.py`?

**Comment by nabilm** [comment]
> @nabilm Thank you for the PR. Can you check the lint results and separate code format from the PR? It is difficult to see difference on `dbt_artifacts_parser/parsers/manifest/manifest_v5.py`?

sure will update asap :)

**Comment by nabilm** [comment]
> @nabilm Thank you for the PR. Can you check the lint results and separate code format from the PR? It is difficult to see difference on `dbt_artifacts_parser/parsers/manifest/manifest_v5.py`?

Done , please check

**Review by yu-iskw — APPROVED** [review]
Thank you for the contribution! I will merge this.

**Comment by nabilm** [comment]
can you please create a release :) , or i should do it, didn't check if i have access to do so

**Pull request merged**
