### PR TITLE
Define and export union types

### PR DESCRIPTION
**Pull request by syou6162**
## Background
If I simply use dbt-artifacts-parser, that is often enough, since types like `ManifestV1` are provided.

However, if a third-party tool that supports various versions of dbt artifacts uses dbt-artifacts-parser (e.g., https://github.com/datnguye/dbterd/pull/86 ), then the ` ManifestV1`, `ManifestV2`, `ManifestV3`, ... types with `Union`.

We did not think it desirable to define these in third-party tools, since every time there is a change in dbt-artifacts-parser, the third-party tool also has to modify the type.

## What I Changed
I defined `Union` types so that they can be used by third-party libraries.

### CODE REVIEW

**Comment by syou6162** [comment]
@yu-iskw Could you review my pull request? CC: @datnguye

**Comment by yu-iskw** [comment]
@syou6162 I'm so sorry for the delay of my reply and thank you for the contribution. As we have supported dbt 1.8 (manifest v12 and run-results v6) are migrating the supported version of pydantic from v1 to v2, we have some conflicts in the pull request. Can you please catch up with the changes?

**Comment by syou6162** [comment]
@yu-iskw Of course! I have just corrected the conflicted content in 0163006. Can you review it again?

**Comment by yu-iskw** [comment]
Unfortunately, it seems that we can't use the type aliasing in python 3.8 and 3.9. The two are sill supported versions, though I am not sure how many users are impacted by cutting them off. Do you have any idea to solve the issue?

https://devguide.python.org/versions/

**Comment by syou6162** [comment]
@yu-iskw Okay, I understand the situation. Since I could not come up with a replacement for `TypeAlias`, how about merge this pull request around 2025-10 when Python 3.9 is `end of life`? I have no problem with waiting until that time. 

CC: @datnguye

**Comment by yu-iskw** [comment]
Alright. Let me close this at the moment. We will have other conflicts as supporting newer versions of dbt, since there is a long time until the end-of-life of the version. Please feel free to reopen it, if it gets ready.

**Pull request closed without merging**
