### PR TITLE
Fixed manifest v11 resource types

### PR DESCRIPTION
**Pull request by OnkarVO7**
Fixes https://github.com/yu-iskw/dbt-artifacts-parser/issues/67

### CODE REVIEW

**Comment by OnkarVO7** [comment]
@yu-iskw could you please review the PR and lets me know if anything else is required. Thanks

**Comment by harshach** [comment]
@yu-iskw appreciate your review here. Our users are running into this bug. Thanks

**Review by yu-iskw — APPROVED** [review]

**Comment by yu-iskw** [comment]
@OnkarVO7 Thank you for the pull request. I have merged and published at v0.5.1. Can make sure if it works in your situation?

https://github.com/yu-iskw/dbt-artifacts-parser/releases/tag/v0.5.1

BTW, I am doubbting the issue is caused by `datamodel-code-generator` with which we generate the pydantic classess from JSON schemas of dbt artifacts. So, we can fix it on the module side, not dbt-core. I will look into it later. 

https://github.com/koxudaxi/datamodel-code-generator/issues/1787

**Comment by OnkarVO7** [comment]
Thanks @yu-iskw . Tested the new release it is working now.

**Pull request merged**
